### ISSUE TITLE
反馈一些问题！

### ISSUE THREAD

**Issue by youshandefeiyang** [pscj/streaming-media-subtitle#1]
.

**Comment by pscj** [comment]
1. 请提供一下使用的设备
2. 作为小众工具，目前暂时无力维护这个字幕库。如果以后用户多了，可以加入自动上传字幕功能，那就能解决部分问题

**Comment by limr95** [comment]
设备是国行索尼电视，阉割了gms的Android TV，可以加下我频道 @yunspeedtest ，我已经将你的这个项目推荐到频道了！

**Comment by limr95** [comment]
也有可能是索尼电视的第三方Laucher的锅！
