### ISSUE TITLE
请问自动匹配字幕的功能无法实现还是其他原因？

### ISSUE THREAD

**Issue by youshandefeiyang** [pscj/streaming-media-subtitle#11]
这个功能挺方便的，如果说有额外花费，那就不说了！

**Comment by pscj** [comment]
字幕下载网站太内卷 各种防盗措施，验证码之类，自动下载不太现实

**Comment by 1999jb** [comment]
3.2成功识别按键调整字幕。现在发现有的字幕插件不识别，无显示，有的字幕正常。估计是字幕文件里的格式问题
