### ISSUE TITLE
3.1版本，音量控制字幕同步问题

### ISSUE THREAD

**Issue by 1999jb** [pscj/streaming-media-subtitle#14]
非常优秀的插件，3.01同步切换回播放略慢。新的3.1调整字幕看不出效果，不知道音量+是字幕提前还是退后。建议保留字幕设置里的同步调整选项。发现3.1打开关闭字幕插件后，却关不了语音辅助，3.01无问题。希望作者能有空研究出亚马逊，孔雀，tubi的字幕插件，就完美了：）

**Comment by pscj** [comment]
请先说一下你使用盒子的具体型号
音量调整字幕屏幕上是会有显示的，如果你的没有，可能是遥控器按键code不匹配。
语音辅助HBOMax里面出声的吗？
amazon你可以买中文帐号嘛，其它2个平台到是还没怎么用过呢

**Comment by 1999jb** [comment]
我用的  mecool kd3,系统是安卓11的Google tv系统，暂停后音量加减还是显示音量变化图标

**Comment by pscj** [comment]
明白了，应该就是按键code不匹配。我想想办法

**Comment by 1999jb** [comment]
亚马逊用的美区，大约1/3有中文，其他还是标配英文或无字幕。孔雀tv和tubi是免费流媒体可以安装到安卓tv上，内容也非常丰富和其他家互补，就是字幕完全无中

**Comment by 1999jb** [comment]
现在上传字幕熟练了也就半分钟，手机下载，解包字幕，上传，插件设置打开链接到新字幕，非常赞👍

**Comment by pscj** [comment]
亚马逊买国际版那个帐号，应该全部有中字的。
你去盒子里装一个软件叫button mapper，里面有个添加按键的功能，在这个地方按下音量的- + 会，看到按键对应的code数字，你把这个数字告诉我。

**Comment by 1999jb** [comment]
所谓亚马逊国际版其实就是港区版，的确是全中文，但老美区的才是真正的prime vedio，影视数量是港区的3倍，电影数量也远超奈飞。正好在使用这个软件，+是166,-是167

**Comment by pscj** [comment]
新发了一版，加上了你这个遥控的音量键支持，可以试试。

**Comment by 1999jb** [comment]
优秀！3.2正常识别按键同步字幕。多看几部后，发现有的字幕文件不识别，没有显示，有的又正常，估计是字幕内部格式问题

**Comment by 1999jb** [comment]
3.2遥控器正常！

**Comment by pscj** [comment]
能用就好，哈哈。这遥控器键位有点乱， 音量+-使用的code是频道的+-

**Comment by 1999jb** [comment]
哈，这也被你看出来。其实我告诉你就是频道加减，这两个键很少用，拿来作调字幕专用键。
