### ISSUE TITLE
只能用在HBOMAX?

### ISSUE THREAD

**Issue by Retsu0907** [pscj/streaming-media-subtitle#15]
既然是用懸浮層的原理加載字幕
那應該所有android TV上的視頻都可以用的，只要找到正確的字幕
像Prime Video, Paramount+, Hulu......
這些能用嗎

**Comment by pscj** [comment]
对，不支持其它的。主要是没有时间线数据

**Comment by Retsu0907** [comment]
能不能做個手動調整時間線的..
我不在意每次看影片都先調時間線

**Comment by pscj** [comment]
目前无此计划做这种纯手工功能
